apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config-map
  namespace: purely
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://registry-svc:80/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "auth-svc"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: purely
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI_AUTH: "mongodb://mongodb-svc:27017/purely_auth_service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: category-config-map
  namespace: purely
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://registry-svc:80/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "category-svc"
---
apiVersion: v1
kind: Secret
metadata:
  name: category-secret
  namespace: purely
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI_CATEGORY: "mongodb://mongodb-svc:27017/purely_category_service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config-map
  namespace: purely
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://registry-svc:80/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "product-svc"
---
apiVersion: v1
kind: Secret
metadata:
  name: product-secret
  namespace: purely
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI_PRODUCT: "mongodb://mongodb-svc:27017/purely_product_service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config-map
  namespace: purely
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://registry-svc:80/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "cart-svc"
---
apiVersion: v1
kind: Secret
metadata:
  name: cart-secret
  namespace: purely
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI_CART: "mongodb://mongodb-svc:27017/purely_cart_service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config-map
  namespace: purely
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://registry-svc:80/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "order-svc"
---
apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: purely
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI_ORDER: "mongodb://mongodb-svc:27017/purely_order_service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config-map
  namespace: purely
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://registry-svc:80/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "user-svc"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: purely
type: Opaque
stringData:
  SPRING_DATA_MONGODB_URI_USER: "mongodb://mongodb-svc:27017/purely_user_service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config-map
  namespace: purely
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://registry-svc:80/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "notification-svc"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: purely
type: Opaque
stringData:
  SPRING_MAIL_USERNAME: "notification@example.com"
  SPRING_MAIL_PASSWORD: "defaultpassword"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config-map
  namespace: purely
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://registry-svc:80/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "gateway-svc"
